name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Install Bundler
        run: gem install bundler

      - name: Install gems
        run: bundle install

      - name: Swift Packages Cache
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            Build/SourcePackages
            Build/Build/Products
          key: ${{ runner.os }}-deps-v1-${{ hashFiles('BILDsolid.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}
          restore-keys: ${{ runner.os }}-deps-v1-

      - name: Upload to test flight
        if: steps.setup.outputs.cache-hit != 'true'
        run: bundle exec fastlane beta
      
      - name: Create Tag
        if: github.ref == 'refs/heads/main'
        run: |
          git config --local user.email "srini2dl@github.com"
          git config --local user.name "srini2dl"
          git tag -a v${{ github.run_number }} -m "Version v${{ github.run_number }}"
          git push origin v${{ github.run_number }}

      - name: Create Release
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            path/to/your/binary
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          body: |
            Release notes go here
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
